#Arquivo de configuração da aplicação Spring Boot do usuario-service.
  #Define propriedades da aplicação como: nome do serviço ; porta do servidor ; configuração do banco de dados ; conexão com o servidor Eureka
  #Essas configurações são carregadas automaticamente quandoa aplicação é iniciada.

spring:
  application:
    name: produto-service # nome do serviço registrado no Eureka
    
  datasource:  # configuração do banco de dados (Oracle)
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: produto_db
    password: 123
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:  # configuração do Hibernate/JPA
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true  

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # endereço do servidor Eureka


      